---
name: "Update contribution snake"

on:
  schedule:
    - cron: "0 22,4,10,16 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  generate:
    name: "Generate contribution snake"
    runs-on: ubuntu-latest

    steps:
      - name: "Generate contribution snake SVG"
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/profile-snake-contrib/github-contribution-grid-snake.svg
            dist/profile-snake-contrib/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: "Upload contribution snake to repository"
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update contribution snake [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
